default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: <%= ENV['DB_PORT'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
development:
  <<: *default
  database: great_test_development